version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
      - "4477:4477"
    environment:
      PRISMA_CONFIG: |
        port: 4477
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
